### ISSUE TITLE
Argument --signal_top_pairs(_rnd) ideas...

### ISSUE THREAD

**Issue by JeeZues** [JeeZues/TradeBot#10]
Hey derrey,

Looking at bot signals:
![image](https://user-images.githubusercontent.com/31246/118049117-423ac900-b34b-11eb-9a57-32e438fc238d.png)

I was thinking maybe we can use the profit % in our calculations...

Here are some data based on **current logic** where we just look for how often we got signals:
`['STMX', 'BAND', 'LINK', 'KNC', 'WAVES', 'ZEC', 'KAVA', 'COMP', 'ICX', 'EOS', 'RLC', 'XLM', 'LTC', 'ADA', 'BNB', 'SRM', 'TRX', 'BAT', 'SXP', 'IOTA', 'BCH', 'ALGO', 'FTM', 'DOT', 'ONE', 'DOGE', 'MANA', 'ANKR', 'THETA', 'STORJ', 'MKR', 'ZIL', 'FLM', 'ALICE', 'ZEN', 'CELR', 'GRT', 'SFP', 'CRV', 'YFII', 'OMG', 'MTL', 'BLZ', 'BTS', 'NKN', 'ONT', 'NEO', 'ATOM', 'HOT', 'ZRX', 'CHR', 'AXS', 'HNT', 'BEL', 'ENJ', 'BTT', 'DASH', 'XRP', 'OCEAN', 'BZRX', 'VET', 'SOL', 'TRB', 'QTUM', 'HBAR', 'XTZ', 'CTK', 'ETC', 'AVAX', 'IOST', 'REN', 'SNX', 'DODO', 'NEAR', 'SAND', 'AAVE', 'REEF', 'RUNE', 'OGN', 'COTI', 'LIT', 'DENT', 'FIL', 'UNI', 'ETH', 'TOMO', 'UNFI', 'MATIC', 'AKRO', 'RVN', 'CHZ', 'BAL', 'LRC', 'YFI', 'XEM', 'SKL', 'DEFI', 'SUSHI', 'CVC', 'LINA', 'RSR', 'KSM', '1INCH', 'LUNA', 'EGLD', 'BTC', 'ALPHA', 'XMR']`

This is the same data as above but aggregating the **min profit %** per coin pair, sorted from highest to lowest:
`['XLM', 'WAVES', 'SRM', 'BAND', 'RLC', 'ZEN', 'GRT', 'FLM', 'COMP', 'AXS', 'SUSHI', 'BZRX', 'YFII', 'AVAX', 'ZEC', 'KNC', 'LTC', 'OGN', 'SNX', 'NKN', 'KAVA', 'YFI', 'MKR', 'ANKR', 'BAT', 'DOGE', '1INCH', 'HBAR', 'UNI', 'HNT', 'RUNE', 'EGLD', 'HOT', 'XTZ', 'LIT', 'REN', 'COTI', 'DASH', 'ICX', 'CVC', 'BTS', 'ZIL', 'CTK', 'RSR', 'IOST', 'ONT', 'RVN', 'STMX', 'LINA', 'BTC', 'BTT', 'DOT', 'BCH', 'ETH', 'XEM', 'NEAR', 'KSM', 'NEO', 'SFP', 'QTUM', 'IOTA', 'FIL', 'BEL', 'LUNA', 'AKRO', 'XMR', 'ALPHA', 'UNFI', 'MATIC', 'ZRX', 'ALICE', 'STORJ', 'TOMO', 'CRV', 'ALGO', 'SAND', 'BLZ', 'XRP', 'ATOM', 'EOS', 'BAL', 'BNB', 'CELR', 'DENT', 'OMG', 'SKL', 'DEFI', 'AAVE', 'OCEAN', 'TRX', 'SOL', 'VET', 'LINK', 'FTM', 'MANA', 'SXP', 'TRB', 'ONE', 'REEF', 'ENJ', 'LRC', 'ADA', 'DODO', 'MTL', 'CHZ', 'CHR', 'THETA', 'ETC']`

This is the same data as above but aggregating the **max profit %** per coin pair, sorted from highest to lowest:
`['RLC', 'BNB', 'DOGE', 'ADA', 'XLM', 'BCH', 'EOS', 'MATIC', 'LTC', 'KAVA', 'KNC', 'WAVES', 'SXP', 'FTM', 'LINK', 'ICX', 'XRP', 'MKR', 'ETH', 'TRX', 'BAND', 'ETC', 'ONT', 'ZIL', 'SRM', 'DOT', 'ALGO', 'IOTA', 'COMP', 'REEF', 'ONE', 'THETA', 'OMG', 'MTL', 'HOT', 'ANKR', 'XTZ', 'TRB', 'BAL', 'VET', 'YFII', 'NEO', 'DASH', 'ALICE', 'QTUM', 'AXS', 'ZEN', 'ZEC', 'HBAR', 'OCEAN', 'RSR', 'ZRX', 'BTT', 'ATOM', 'ENJ', 'CHZ', 'BAT', 'STORJ', 'BEL', 'AVAX', 'IOST', 'CRV', 'ALPHA', 'XEM', 'GRT', 'AKRO', 'BZRX', 'CHR', 'MANA', 'FLM', 'REN', '1INCH', 'FIL', 'LIT', 'YFI', 'BLZ', 'DENT', 'COTI', 'SFP', 'NEAR', 'RVN', 'AAVE', 'OGN', 'DODO', 'BTS', 'SNX', 'SUSHI', 'RUNE', 'LRC', 'LINA', 'UNI', 'XMR', 'HNT', 'SAND', 'DEFI', 'EGLD', 'CELR', 'STMX', 'NKN', 'UNFI', 'SOL', 'CTK', 'CVC', 'SKL', 'TOMO', 'KSM', 'BTC', 'LUNA']`

Do you think the new ones based on profit % would provide a better indicator of what pairs we should rank higher?  And if so, min or max?

**Comment by JeeZues** [comment]
Added optional augments for --signal_top_pairs
You can call with --signal_top_pairs for current default (sort by count of signals)
you can also use --signal_top_pairs min or --signal_top_pairs max to sort by %profit min or max from signal history instead of default count of signals

**Comment by derrey** [comment]
I am not sure 3C profit % are correct at all as they don't follow the DCA rules when calculating them. I have reached out the the 3C API devs to see if we can get much less delay on signals as I think that is a moving market the more current signal counts would be much better. I have been testing the new settings and getting over 2.5%-4% per day depending on the settings. rnd vs top. The top are doing better than rnd. so with more current data, we may do better.
