### ISSUE TITLE
Feature request: Adapt to new SDCA strategy, dynamic TPs based on SO 

### ISSUE THREAD

**Issue by UC-VR** [JeeZues/TradeBot#13]
As per recently released SDCA strategy, it would be great if TradeBot could start changing TP% based on current SO, with configurable settings (% per SO).

for example:
SO 1-4 = default
SO5 = 1%
SO6 = 2%
SO7 = 3%

Thank you!

**Comment by derrey** [comment]
> As per recently released SDCA strategy, it would be great if TradeBot could start changing TP% based on current SO, with configurable settings (% per SO).
> 
> for example:
> SO 1-4 = default
> SO5 = 1%
> SO6 = 2%
> SO7 = 3%
> 
> Thank you!

Was this strategy for Futures accounts? I thought it was just for the standard DCA non-leveraged strategy.
I am not sure I would want to wait for a 3% on a 50x Futures contract.. maybe I missed something.

**Comment by UC-VR** [comment]
You are right, for SPOT only.

I've tested something similar manually on Futures, with some custom TPs. 

But you are right, this is too risky to work well in autonomous mode.

**Comment by JeeZues** [comment]
@UC-VR @derrey 
I added that option no the less :)

**Comment by derrey** [comment]
@JeeZues will TradeBot work on standard DCA bots using this method? I have not testing or really thought this through yet.. just a curiosity question. With the new BPT SDCA settings, I was thinking that this could work at the BOT level and adjust the deals for that bot. (Still not sure if it is a good idea to fully automate this yet, but willing to try on some select bots)

**Comment by derrey** [comment]
@UC-VR Can you reopen this issue so we can discuss this for SPOT usage?
