### ISSUE TITLE
Stuck missing trades?

### ISSUE THREAD

**Issue by derrey** [JeeZues/TradeBot#4]
Hi, I have both scripts stuck with missing trades that keep looping.
I have looked and they are not showing on 3C and have stopped and started them again, but they keep looping as if they just closed but never go away.
Are any of your's doing that?
![image](https://user-images.githubusercontent.com/5298725/117369259-af091b80-ae92-11eb-9b9a-a9489b0e7336.png)

**Comment by derrey** [comment]
I have finally found the problem with the deals. They are the orphan deals from 3C messing up.. you have to go deep into the Open Orders tab way at the bottom of the account page for the account that has the error. Then match up all your open trades to your bots. When you find open orders without any bots running with that pair... you need to cancel that one. Check each one.

**Comment by JeeZues** [comment]
Ya, 3C and Binance sometimes have issues talking to each other... I report on anything in one side and not the other.  If you see it repeat from one snapshot to the next it is usually an issue that needs addressing manually.  Sometimes when you only see it once it normal as deals open/refresh on one side before the other...
I started on some logic to make better "guesses" on if it's an issue or not but haven't had much time lately to formalize it.  This like if the deal age is very recent to not mark it as an error etc.
