### ISSUE TITLE
Long bots only?

### ISSUE THREAD

**Issue by derrey** [JeeZues/TradeBot#6]
I have not tested this yet, but will this program handle accounts that only have LONG bots turned on?
i.e. turned off all shorts during some issues.

**Comment by JeeZues** [comment]
there is a big (bad) assumption in the code that longs and shorts exists side by side, when I do counting/etc. I only look at longs.  There is a chance it might work as is.
It's on my to do list to disable shorts as well.  They only cause issues in specific market types and return on them is around 10% of longs which I'm willing to ignore for reduced risk.
I'm thinking of a new flag, e.g. --no_short, that should fully ignore shorts when starting/stopping bots...

**Comment by JeeZues** [comment]
on thing I forgot to mention, feel free making code changes through pull requests.  I'll look at it and for sure consider merging them :)

**Comment by derrey** [comment]
> on thing I forgot to mention, feel free making code changes through pull requests. I'll look at it and for sure consider merging them :)

Thanks.. I am a programmer for over 30 years... but have not done much in Python (Very little), so I don't think I can add much. I can come up with ideas thought :)

**Comment by derrey** [comment]
I have a new account with 5K running with just LONG as a test. So far so good.. it has activated 30 pairs now.
2 have opened.. I will see how it goes. 

![image](https://user-images.githubusercontent.com/5298725/117506203-374ef580-af53-11eb-8f70-768aa4b239c9.png)
![image](https://user-images.githubusercontent.com/5298725/117506264-4c2b8900-af53-11eb-938f-18fb3bc242b2.png)

**Comment by JeeZues** [comment]
I added the --no_short argument in case you have both bots (as recommended) there and only want to start the long ones.
Python is very easy, specially the way I write it :)
I'm still kind of stuck in the procedural world and avoid the complexity of classes, etc.  I guess I'm stuck in my old ways...

**Comment by derrey** [comment]
I am testing them both tonight on 3 accounts. I will close this for now. Thanks again!!! 👍
