### ISSUE TITLE
Feature request: cheaper fee crypto for donation 

### ISSUE THREAD

**Issue by UC-VR** [JeeZues/TradeBot#9]
Thanks again for sharing your tool!

Could you please add and share few more crypto addresses to buy you beers? :)

It's a pity to pay 20-40 fiat in fees for ETH or BTC.

LTC or XTZ for example? :)

**Comment by JeeZues** [comment]
Done, thank you

**Comment by UC-VR** [comment]
few beers + few snacks sent of tezos

thanks a lot of your work!
